### ISSUE TITLE
problems during ./configure

### ISSUE THREAD

**Issue by PavloFatula** [dashesy/cc-tool#12]
I'm trying to build this lib on Ubuntu 19.04 but facing with failure during ./configure execution: 
`checking boost/crc.hpp presence... yes
checking for boost/crc.hpp... yes
./configure: line 13102: syntax error near unexpected token `LIBUSB,'
./configure: line 13102: `PKG_CHECK_MODULES(LIBUSB, libusb-1.0 >= 1.0.0)'
`
dh-autoreconf, libusb-1.0.0, libboost-all-dev packages were installed. 
make file is not generated.

please help me to understand where is the problem

**Comment by PavloFatula** [comment]
I've installed libusb-dev and libglib2.0-dev 

so I've search for dependencies by apt-cache search libusb-1.0
and installed all of them (in my case sudo apt-get install libusb-ocaml libusb-ocaml-dev lm4flash )
and it seems that configure was able to finish w/o errors

please not forget to do make clean before doing configure one more time

**Comment by PavloFatula** [comment]
closing issue as I was able to run cc-tool

**Comment by ChrisChoke** [comment]
Hey,

same issue here with ubuntu 18.04.4.
needed to install the package `libusb-1.0-0-dev` additionally. then the configure run became done successfull. so everything is fine. maybe just updating the readme.

best regards
Chris
