### ISSUE TITLE
Unable to compile on Linux Mint 19.1 Cinnamon

### ISSUE THREAD

**Issue by kjlisby** [dashesy/cc-tool#9]
I am having problems in running ./configure. The last few lines of output look like this:

_checking whether we are using the GNU C++ compiler... no
checking whether g++ accepts -g... no
checking for Boost headers version >= 1.39.0... no
configure: error: cannot find Boost headers version >= 1.39.0_

I have a lot of boost stuff installed:
$ _apt list --installed | grep libboost-all-dev
libboost-all-dev/bionic,now 1.65.1.0ubuntu1 amd64 [installed]_

I cannot figure out what I am doing wrong.

**Comment by ayekat** [comment]
> *checking whether we are using the GNU C++ compiler... no*
> *checking whether g++ accepts -g... no*

Is g++ installed?

**Comment by kjlisby** [comment]
Spot on! Installing g++ did the trick. Thank you very much.
I thought it was sufficient to have gcc.
